'use client';
import React,{useEffect,useRef,useState,useCallback} from 'react';
import {Player,type PlayerRef} from '@remotion/player';
import {Clapperboard,FolderOpen,FileText,Mic,Layers,Download,Plus,Upload,ChevronDown,Check,ArrowRight,Image as ImageIcon,Film,Music2,Volume2,Trash2,ArrowUp,ArrowDown,Settings2,Palette,Clock3,LoaderCircle,ExternalLink,RefreshCw,AlertCircle,Save,BookOpen,X,Monitor,Link2,Scissors,Play,CheckCircle2} from 'lucide-react';
import {NewsVideo} from '@/video/NewsVideo';
import {type Project,type Scene,type Asset,type Job,dimensions,durationFrames,timeline,sceneFrames,assetUrl,FPS,newScene,toSrt,validateProject,textChunks} from '@/lib/model';

import {STUDIO_TEMPLATES,LEGACY_TEMPLATES,defaultDesign} from '@/lib/templates';
import {PlatformGuide} from './PlatformGuide';
import {PHONE,PREVIEW_VIDEO,PLATFORMS,type SocialPlatform} from '@/lib/platforms';
import {MediaControls,BodyFraming} from './MediaControls';
import {bodySceneFromMedia} from '@/lib/media-scenes';
import {FrameControls} from './FrameControls';
import {CustomStyles} from './CustomStyles';
import {analyzeStyleImage,customStyleName} from '@/lib/custom-style';
import {TemplateSwatch} from './TemplateSwatch';
import {PublishingPanel} from './PublishingPanel';
import type {ArticleImport} from '@/lib/article-import';

type Stage='input'|'script'|'voice'|'studio'|'output';
const stages:{id:Stage;label:string;icon:typeof FolderOpen;hint:string}[]=[{id:'input',label:'Input',icon:FolderOpen,hint:'Tư liệu & nguồn tin'},{id:'script',label:'Kịch bản',icon:FileText,hint:'Biên tập câu chuyện'},{id:'voice',label:'Voice',icon:Mic,hint:'Giọng đọc của bản tin'},{id:'studio',label:'Studio',icon:Layers,hint:'Dựng hình & nhận diện'},{id:'output',label:'Output',icon:Download,hint:'Kiểm duyệt & xuất video'}];

const kindName={intro:'Mở đầu',body:'Nội dung'};
const formatTime=(seconds:number)=>`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(Math.floor(seconds%60)).padStart(2,'0')}`;
async function api<T>(url:string,body?:unknown,method?:string):Promise<T>{const res=await fetch(url,body?{method:method||'POST',headers:body instanceof FormData?undefined:{'Content-Type':'application/json'},body:body instanceof FormData?body:JSON.stringify(body)}:undefined);const json=await res.json();if(!res.ok)throw new Error(json.error||'Không thể kết nối server.');return json;}
function downloadText(name:string,text:string,type='text/plain;charset=utf-8'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}

export default function Studio(){
 const [project,setProject]=useState<Project|null>(null);const current=useRef<Project|null>(null);const [projects,setProjects]=useState<Project[]>([]);
 const [stage,setStage]=useState<Stage>('input');const [selected,setSelected]=useState('');const [dirty,setDirty]=useState(false);const dirtyRef=useRef(false);const saving=useRef<Promise<Project>|null>(null);
 const [saveState,setSaveState]=useState('Đã lưu');const [busy,setBusy]=useState('');const [error,setError]=useState('');const [notice,setNotice]=useState('');
 const [jobs,setJobs]=useState<Job[]>([]);const knownJobs=useRef(new Map<string,string>());
 const [status,setStatus]=useState<{worker:boolean;providers:{vbee:boolean;azure:boolean;vbeeVoice:string}}|null>(null);
 const [articleImport,setArticleImport]=useState<ArticleImport>();
 const [sourceUrl,setSourceUrl]=useState('');const [sourcePreview,setSourcePreview]=useState<Project['source']>();
 const [provider,setProvider]=useState<'vbee'|'azure'>('vbee');const [voiceId,setVoiceId]=useState('hn_female_ngochuyen_full_48k-fhg');const [speed,setSpeed]=useState(1);
 const [preset,setPreset]=useState<'draft'|'full'>('full');const [approved,setApproved]=useState(false);const [settings,setSettings]=useState(false);
 const [previewPlatform,setPreviewPlatform]=useState<SocialPlatform>('tiktok');
 const [showReference,setShowReference]=useState(false);const [showPlatform,setShowPlatform]=useState(true);const [playing,setPlaying]=useState(false);
 const [frame,setFrame]=useState(0);const player=useRef<PlayerRef>(null);const fileInput=useRef<HTMLInputElement>(null);const bodyInput=useRef<HTMLInputElement>(null);const voiceInput=useRef<HTMLInputElement>(null);const logoInput=useRef<HTMLInputElement>(null);const musicInput=useRef<HTMLInputElement>(null);
 const setCurrent=useCallback((p:Project,isDirty=false)=>{current.current=p;setProject(p);dirtyRef.current=isDirty;setDirty(isDirty);setApproved(false);if(isDirty)setSaveState('Chưa lưu');},[]);
 useEffect(()=>{let alive=true;(async()=>{try{const list=await api<Project[]>('/api/projects');if(!alive)return;let p=list[0];const saved=localStorage.getItem('crevid-project');if(saved)p=list.find(x=>x.id===saved)||p;if(!p)p=await api<Project>('/api/projects',{title:'Bản tin đầu tiên'});if(!alive)return;setProjects(list.length?list:[p]);const savedPlatform=localStorage.getItem('crevid-preview-platform');setPreviewPlatform(savedPlatform&&savedPlatform in PLATFORMS?savedPlatform as SocialPlatform:p.design.platform||'tiktok');setCurrent(p);setSelected(p.scenes[0].id);}catch(e){setError((e as Error).message);}})();return()=>{alive=false;};},[setCurrent]);
 const patch=(fn:(p:Project)=>Project)=>{if(!current.current)return;setCurrent(fn(current.current),true);};
 const patchScene=(changes:Partial<Scene>)=>patch(p=>({...p,scenes:p.scenes.map(s=>s.id===selected?{...s,...changes}:s)}));
 const save=useCallback(async():Promise<Project>=>{
  while(saving.current)await saving.current;
  const p=current.current!;if(!dirtyRef.current)return p;
  setSaveState('Đang lưu…');
  const promise=api<Project>(`/api/projects/${p.id}`,p,'PUT');saving.current=promise;
  try{const saved=await promise;if(current.current===p){setCurrent(saved);setSaveState('Đã lưu');}else{setCurrent({...current.current!,revision:saved.revision,assets:saved.assets},true);}
   setProjects(list=>list.map(x=>x.id===saved.id?saved:x));return saved;
  }catch(e){setSaveState('Lỗi lưu');setError((e as Error).message);throw e;}finally{saving.current=null;}
 },[setCurrent]);
 useEffect(()=>{if(!dirty||busy)return;const timer=setTimeout(()=>void save().catch(()=>{}),1800);return()=>clearTimeout(timer);},[project,dirty,busy,save]);
 useEffect(()=>{const listener=(e:BeforeUnloadEvent)=>{if(dirtyRef.current){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',listener);return()=>window.removeEventListener('beforeunload',listener);},[]);
 useEffect(()=>{if(!project)return;localStorage.setItem('crevid-project',project.id);let active=true;
  const poll=async()=>{try{const [nextJobs,nextStatus]=await Promise.all([api<Job[]>(`/api/actions?projectId=${project.id}`),api<NonNullable<typeof status>>('/api/status')]);if(!active)return;setJobs(nextJobs);setStatus(nextStatus);
   const newVoice=nextJobs.some(j=>j.kind==='voice'&&j.state==='succeeded'&&knownJobs.current.has(j.id)&&knownJobs.current.get(j.id)!=='succeeded');nextJobs.forEach(j=>knownJobs.current.set(j.id,j.state));
   if(newVoice){if(!dirtyRef.current&&!saving.current){const before=current.current;const p=await api<Project>(`/api/projects/${project.id}`);if(active&&current.current===before&&!dirtyRef.current)setCurrent(p);}else setNotice('Voice đã tạo xong. Lưu hoặc tải lại dự án để nhận audio mới.');}
  }catch(e){if(active)setError((e as Error).message);}};void poll();const timer=setInterval(poll,2500);return()=>{active=false;clearInterval(timer);};
 },[project?.id,setCurrent]);
 useEffect(()=>{const p=player.current;if(!p)return;const listener=({detail}:{detail:{frame:number}})=>setFrame(detail.frame);const onPlay=()=>setPlaying(true);const onPause=()=>setPlaying(false);p.addEventListener('frameupdate',listener);p.addEventListener('play',onPlay);p.addEventListener('pause',onPause);return()=>{p.removeEventListener('frameupdate',listener);p.removeEventListener('play',onPlay);p.removeEventListener('pause',onPause);};},[project?.id]);
 const run=async(label:string,fn:()=>Promise<void>)=>{setBusy(label);setError('');setNotice('');try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy('');}};
 const switchProject=async(id:string)=>run('Đang mở dự án',async()=>{await save();const p=await api<Project>(`/api/projects/${id}`);setCurrent(p);setSelected(p.scenes[0].id);setSaveState('Đã lưu');setArticleImport(undefined);setSourcePreview(undefined);setFrame(0);knownJobs.current.clear();});
 const createProject=()=>run('Đang tạo dự án',async()=>{await save();const p=await api<Project>('/api/projects',{title:`Bản tin ${projects.length+1}`});setProjects(list=>[p,...list]);setCurrent(p);setSelected(p.scenes[0].id);setStage('input');setSaveState('Đã lưu');});
 const upload=async(files:FileList|File[]|null,role:'media'|'voice'|'logo'|'music'|'style'|'body'='media',styleLayout:'lower-third'|'popup'='lower-third')=>{
  if(!files?.length)return;
  const selectedFiles=Array.from(files);
  await run('Đang tải và xử lý tư liệu',async()=>{
   const allowed=role==='body'?/\.(png|jpe?g|webp|mp4|mov)$/i:(role==='logo'||role==='style')?/\.(png|jpe?g|webp)$/i:role==='music'||role==='voice'?/\.(mp3|wav|m4a)$/i:null;
   if(allowed&&selectedFiles.some(file=>!allowed.test(file.name)))throw new Error(role==='body'?'Chọn ảnh PNG/JPG/WebP hoặc video MP4/MOV.':(role==='logo'||role==='style')?'Chọn ảnh PNG, JPG hoặc WebP.':'Chọn file âm thanh MP3, WAV hoặc M4A.');
   await save();
   if(current.current!.assets.length+selectedFiles.length>50)throw new Error('Mỗi dự án tối đa 50 tư liệu.');
   if(role==='body'&&current.current!.scenes.length+selectedFiles.length>30)throw new Error('Mỗi dự án tối đa 30 cảnh. Chọn ít file hơn hoặc xóa cảnh không dùng.');
   let firstBodyId='';let createdCount=0;
   try{for(const file of selectedFiles){
    const form=new FormData();form.set('projectId',current.current!.id);form.set('file',file);
    const result=await api<{asset:Asset;project:Project}>('/api/actions',form);let p=result.project;
    const expected=(role==='logo'||role==='style')?'image':role==='voice'||role==='music'?'audio':undefined;
    if(expected&&result.asset.kind!==expected){setCurrent(p);throw new Error('File đã nhập vào thư viện nhưng không đúng loại để gắn vào mục này.');}
    if(role==='voice')p={...p,scenes:p.scenes.map(s=>s.id===selected?{...s,voice:{assetId:result.asset.id,text:s.text,provider:'upload',voiceId:''}}:s)};
    if(role==='logo')p={...p,brand:{...p.brand,logoId:result.asset.id}};
    if(role==='style'){
     setCurrent(p);if((p.customStyles||[]).length>=20)throw new Error('Dự án đã có 20 giao diện custom.');
     const palette=await analyzeStyleImage(assetUrl(p,result.asset.id)!);const style={id:`style-${result.asset.id}`,name:customStyleName(file.name,palette),assetId:result.asset.id,layout:styleLayout,mode:'adapt' as const,...palette,roundness:24};
     p={...p,template:'custom',customStyleId:style.id,customStyles:[...(p.customStyles||[]),style]};
    }
    if(role==='body'&&result.asset.kind==='audio'){setCurrent(p);throw new Error('File đã nhập nhưng chỉ có âm thanh; chọn video có hình để tạo Nội dung.');}
    if(role==='body'){const created=bodySceneFromMedia(result.asset);p={...p,scenes:[...p.scenes,created]};firstBodyId||=created.id;}
    if(role==='music')p={...p,musicId:result.asset.id};
    setCurrent(p,role!=='media');if(role!=='media')await save();if(role==='body')createdCount++;
   }}catch(e){throw new Error(`${createdCount?`Đã tạo ${createdCount} cảnh. `:''}${(e as Error).message}`);}finally{
    if(firstBodyId){setSelected(firstBodyId);setStage('studio');player.current?.seekTo(timeline(current.current!).find(x=>x.scene.id===firstBodyId)?.from||0);}
   }
   setNotice(role==='body'?`Đã tạo ${createdCount} cảnh Nội dung, mỗi ảnh/video một cảnh. Nhập lời đọc và chọn hiệu ứng trong Thuộc tính cảnh.`:role==='style'?'Đã tạo giao diện từ bảng màu của ảnh. Bạn có thể đổi tên và chỉnh màu.':role==='logo'?'Đã tải và gắn logo vào dự án.':role==='music'?'Đã tải và gắn nhạc nền vào dự án.':role==='voice'?'Đã tải và gắn giọng đọc vào cảnh.':'Tư liệu đã sẵn sàng. Chọn một file để gắn vào cảnh.');
  });
 };
 const startRender=()=>run('Đang xếp hàng render',async()=>{const p=await save();const job=await api<Job>('/api/actions',{action:'render',projectId:p.id,revision:p.revision,preset,approved});setJobs(list=>[job,...list.filter(j=>j.id!==job.id)]);setNotice('Đã gửi render. Bạn có thể tiếp tục biên tập.');});
 const importFromUrl=(url:string)=>run('Đang lấy bài, ảnh và đề xuất kịch bản…',async()=>{
  const p=await save();
  const result=await api<ArticleImport>('/api/actions',{action:'import',projectId:p.id,url});
  setArticleImport(result);setSourcePreview(result.source);setCurrent({...result.project,source:result.source},true);setStage('script');
  setNotice(`Đã đề xuất ${result.draft.scenes.length} cảnh và nhập ${result.imported} ảnh. Kiểm tra bản nháp trước khi áp dụng.`);
 });
 const applyDraft=()=>{if(!articleImport)return;const {draft,source}=articleImport;
  patch(p=>{const images=p.assets.filter(a=>a.kind==='image'&&a.sourceUrl&&source.images?.includes(a.sourceUrl));return {...p,title:draft.title.slice(0,100),newsTitle:draft.title,source,scenes:draft.scenes.map((s,i)=>({...s,mediaId:images.length?images[i%images.length].id:undefined}))};});
  setSelected(draft.scenes[0].id);setArticleImport(undefined);setNotice('Đã áp dụng kịch bản và gắn ảnh. Bạn có thể sửa từng cảnh, sau đó tạo giọng đọc.');
 };
 if(!project)return <div className="boot"><div className="app-mark"><Clapperboard/></div><h1>Cre-vid</h1><p>{error||'Đang mở không gian sáng tạo…'}</p>{error&&<button onClick={()=>location.reload()}>Thử lại</button>}</div>;
 const phonePreview=showPlatform&&project.aspect==='9:16';const platformPreset=PLATFORMS[previewPlatform];
 const scene=project.scenes.find(s=>s.id===selected)||project.scenes[0];const selectedIndex=project.scenes.findIndex(s=>s.id===scene.id);const d=dimensions(project.aspect);const total=durationFrames(project);const errors=validateProject(project);const voiceAsset=project.assets.find(a=>a.id===scene.voice?.assetId);const selectedMedia=project.assets.find(a=>a.id===scene.mediaId);const stageInfo=stages.find(x=>x.id===stage)!;const hasPending=jobs.some(j=>['queued','running'].includes(j.state));
 const chooseScene=(s:Scene)=>{setSelected(s.id);player.current?.seekTo((timeline(project).find(x=>x.scene.id===s.id)?.from||0)+12);};
 return <div className="app-shell">
  <aside className="rail"><div className="app-mark"><Clapperboard size={23}/></div><button className="rail-button active" title="Studio" onClick={()=>setStage('input')}><Layers size={21}/></button><button className="rail-button" title="Tạo dự án" onClick={createProject} disabled={!!busy}><Plus size={22}/></button><div className="rail-bottom"><button className="rail-button" title="Cấu hình giọng đọc" onClick={()=>setSettings(true)}><Settings2 size={21}/></button><div className="avatar">CV</div></div></aside>
  <div className="workspace">
   <header className="topbar"><div className="brand-word">Cre-vid<span>STUDIO</span></div><div className="header-divider"/><div className="project-switch"><input disabled={!!busy} aria-label="Tên dự án" value={project.title} maxLength={100} onChange={e=>patch(p=>({...p,title:e.target.value}))}/><select disabled={!!busy} aria-label="Mở dự án" value={project.id} onChange={e=>void switchProject(e.target.value)}>{projects.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></div><div className="topbar-right"><span className={`saved ${dirty?'unsaved':''}`}>{saveState==='Đã lưu'?<Check size={14}/>:<Clock3 size={14}/>} {saveState}</span><button className="button quiet" aria-label="Lưu dự án" title="Lưu dự án" disabled={!!busy} onClick={()=>void run('Đang lưu',async()=>{await save();})}><Save size={16}/></button><button className="button primary" onClick={()=>setStage('output')}>Xuất video <ArrowRight size={15}/></button></div></header>
   <nav className="workflow">{stages.map((s,i)=><React.Fragment key={s.id}><button aria-label={s.label} className={stage===s.id?'step selected':'step'} onClick={()=>setStage(s.id)}><span className="step-number">{i+1}</span><s.icon size={16}/>{s.label}</button>{i<4&&<span className="step-connector"/>}</React.Fragment>)}<span className="workflow-note"><span className="live-dot"/> Không gian cá nhân</span></nav>
   {(error||notice||busy)&&<div className={`notification ${error?'error':''}`} role={error?'alert':'status'}>{busy?<LoaderCircle size={16} className="spin"/>:error?<AlertCircle size={16}/>:<CheckCircle2 size={16}/>}<span>{error||busy||notice}</span>{!busy&&<button aria-label="Đóng thông báo" onClick={()=>{setError('');setNotice('');}}><X size={15}/></button>}{error&&<button onClick={()=>void run('Đang tải lại',async()=>{const p=await api<Project>(`/api/projects/${project.id}`);setCurrent(p);setSaveState('Đã lưu');})}>Tải lại bản đã lưu</button>}</div>}
   <main className="editor-grid" inert={busy?true:undefined}>
    <section className="asset-panel"><div className="panel-heading"><div><span className="eyebrow">NEWSROOM WORKFLOW</span><h1>{stageInfo.hint}</h1></div><span className="count-badge">0{stages.findIndex(s=>s.id===stage)+1}</span></div>
     <div className="panel-scroll">
      {stage==='input'&&<>
       <div className="dropzone" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();void upload(e.dataTransfer.files);}}><span className="upload-icon"><Upload size={24}/></span><h3>Mỗi câu chuyện bắt đầu<br/>từ một góc nhìn.</h3><p>Kéo thả ảnh, video hoặc âm thanh vào đây</p><button className="button secondary" disabled={!!busy} onClick={()=>fileInput.current?.click()}><Plus size={15}/> Thêm tư liệu</button><small>JPG, PNG, WEBP, MP4, MOV · tối đa 100 MB/file</small></div>
       <button className="button secondary full" disabled={!!busy||project.scenes.length>=30} onClick={()=>bodyInput.current?.click()}><Upload size={15}/> Tải nhiều ảnh/video → tạo Nội dung</button>
       <div className="section-label">THƯ VIỆN TƯ LIỆU <span>{project.assets.length} file</span></div>
       {project.assets.length===0?<div className="empty-library"><ImageIcon size={18}/><p>Tư liệu của bạn sẽ xuất hiện ở đây.<br/><span>Bạn có thể dùng nền mẫu để thử dựng ngay.</span></p></div>:<div className="asset-grid">{project.assets.map(a=><button key={a.id} className={`asset-card ${scene.mediaId===a.id?'chosen':''}`} onClick={()=>a.kind==='audio'?patchScene({voice:{assetId:a.id,text:scene.text,provider:'upload',voiceId:''}}):patchScene({mediaId:a.id})}>{a.kind==='image'?<img src={assetUrl(project,a.id)} alt={a.name}/>:a.kind==='video'?<video src={assetUrl(project,a.id)} muted preload="metadata"/>:<div className="audio-tile"><Music2/></div>}<div className="asset-caption"><span>{a.name}</span><small>{a.duration?`${a.duration.toFixed(1)}s`:a.kind==='image'?'Ảnh':'Audio'}</small></div>{scene.mediaId===a.id&&<span className="asset-check"><Check size={12}/></span>}</button>)}</div>}
       <div className="source-box"><div><Link2 size={17}/><h3>Lấy nội dung từ bài báo</h3></div><p>Dán URL để tự lấy ảnh và đề xuất kịch bản, lời mở đầu cùng cách đọc.</p><div className="input-action"><input aria-label="URL bài báo" placeholder="https://…" value={sourceUrl} onChange={e=>setSourceUrl(e.target.value)} onPaste={e=>{const url=e.clipboardData.getData('text').trim();if(/^https?:\/\//i.test(url)){e.preventDefault();setSourceUrl(url);void importFromUrl(url);}}} onKeyDown={e=>{if(e.key==='Enter'&&sourceUrl)void importFromUrl(sourceUrl);}}/><button aria-label="Lấy bài báo" disabled={!sourceUrl||!!busy} onClick={()=>void importFromUrl(sourceUrl)}><ArrowRight size={18}/></button></div></div>
       {sourcePreview&&<div className="source-result"><h3>{sourcePreview.title}</h3><textarea aria-label="Nội dung bài nguồn" rows={7} value={sourcePreview.text} onChange={e=>setSourcePreview({...sourcePreview,text:e.target.value})}/><button className="button secondary" onClick={()=>{patch(p=>({...p,source:sourcePreview}));setStage('script');}}>Lưu nguồn & biên tập <ArrowRight size={15}/></button></div>}
      </>}
      {stage==='script'&&<>
       {articleImport&&<div className="script-proposal"><span className="eyebrow">BẢN NHÁP TỪ BÀI BÁO</span><h3>{articleImport.draft.title}</h3><p>{articleImport.draft.note}</p><div className="proposal-scenes">{articleImport.draft.scenes.map((s,i)=><details key={s.id} open={i===0}><summary>{i+1}. {kindName[s.kind]} · {s.duration}s</summary><p>{s.text}</p><small>{s.voiceDirection}</small></details>)}</div>{articleImport.warnings.map((w,i)=><p key={i} className="warning-text">{w}</p>)}<button className="button primary full" onClick={applyDraft}>Dùng bản nháp & gắn ảnh</button><small>Thao tác này thay các cảnh hiện tại. Phiên bản đã lưu vẫn được giữ trong lịch sử trên máy.</small><button className="text-button" onClick={()=>setArticleImport(undefined)}>Giữ kịch bản hiện tại</button></div>}

       <div className="info-box"><FileText size={19}/><div><strong>Viết để người xem muốn nghe.</strong><p>Chia câu chuyện thành mở đầu và các đoạn nội dung. Lời đọc có thể khác tiêu đề trên hình.</p></div></div>
       {project.source&&<details className="source-details"><summary>Nguồn: {project.source.title}</summary><p>{project.source.text}</p><button className="button secondary" onClick={()=>patchScene({text:project.source!.text.slice(0,3000),source:new URL(project.source!.url).hostname})}>Dùng cho cảnh đang chọn</button></details>}
       <div className="section-label">CẢNH {String(selectedIndex+1).padStart(2,'0')} <span>{kindName[scene.kind]}</span></div>
       <label>Tiêu đề cảnh<textarea aria-label="Tiêu đề cảnh" rows={3} maxLength={180} value={scene.headline} onChange={e=>patchScene({headline:e.target.value})}/><small>{scene.headline.length}/140 ký tự khuyến nghị</small></label>
       <label>Lời đọc<textarea aria-label="Lời đọc" rows={8} maxLength={3000} value={scene.text} onChange={e=>patchScene({text:e.target.value})}/><small>{scene.text.length} ký tự · Vbee tối đa 300 ký tự/đoạn</small></label>
       <button className="button secondary full" onClick={()=>{const chunks=textChunks(scene.text,260);if(chunks.length<2){setNotice('Lời đọc đã đủ ngắn để tạo voice.');return;}patch(p=>({...p,scenes:p.scenes.flatMap(s=>s.id!==scene.id?[s]:chunks.map((text,i)=>i===0?{...s,text,voice:undefined}:{...newScene(),text,headline:s.headline,mediaId:s.mediaId,source:s.source,bodyLayout:s.bodyLayout,bodyOffsetY:s.bodyOffsetY,motion:s.motion,motionAmount:s.motionAmount,fit:s.fit,cropX:s.cropX,cropY:s.cropY,trimStart:s.trimStart,muteOriginal:s.muteOriginal,signOpacity:s.signOpacity}))}));}}><Scissors size={15}/> Chia thành các đoạn ngắn</button>
       <label>Gợi ý cách đọc<textarea aria-label="Gợi ý cách đọc" rows={3} maxLength={500} value={scene.voiceDirection||''} onChange={e=>patchScene({voiceDirection:e.target.value})}/><small>Chỉ dẫn cho biên tập viên; không đưa vào lời đọc.</small></label><label>Ghi nguồn hiển thị<input aria-label="Nguồn hiển thị" value={scene.source} maxLength={180} placeholder="Tên báo / tác giả / đơn vị" onChange={e=>patchScene({source:e.target.value})}/></label>
      </>}
      {stage==='voice'&&<>
       <div className="voice-hero"><div className="voice-avatar"><Mic size={28}/></div><span className="eyebrow">AI VOICE</span><h2>Một giọng nói.<br/>Một dấu ấn riêng.</h2><p>Tạo lời dẫn cho từng cảnh hoặc dùng bản thu của bạn.</p></div>
       {scene.voiceDirection&&<div className="info-box"><Mic size={18}/><div><strong>Cách đọc gợi ý</strong><p>{scene.voiceDirection}</p><small>TTS hiện dùng lời đọc và tốc độ; sắc thái cần nghe thử.</small></div></div>}
       <label>Nhà cung cấp<select value={provider} onChange={e=>{const next=e.target.value as 'vbee'|'azure';setProvider(next);setVoiceId(next==='vbee'?(status?.providers.vbeeVoice||'hn_female_ngochuyen_full_48k-fhg'):'vi-VN-HoaiMyNeural');}}><option value="vbee">Vbee · Ngọc Huyền</option><option value="azure">Azure Speech · Tiếng Việt</option></select></label>
       {provider==='azure'?<label>Giọng đọc<select value={voiceId} onChange={e=>setVoiceId(e.target.value)}><option value="vi-VN-HoaiMyNeural">Hoài My · Nữ</option><option value="vi-VN-NamMinhNeural">Nam Minh · Nam</option></select></label>:<div className="voice-choice"><span className="mini-avatar">NH</span><div><strong>Ngọc Huyền</strong><small>Tiếng Việt · Nữ · Vbee</small></div><CheckCircle2 size={18}/></div>}
       <label>Tốc độ đọc <span className="value-badge">{speed.toFixed(1)}×</span><input type="range" min="0.5" max="1.5" step="0.1" value={speed} onChange={e=>setSpeed(Number(e.target.value))}/></label>
       <div className="voice-excerpt"><span className="eyebrow">LỜI ĐỌC · CẢNH {selectedIndex+1}</span><p>{scene.text||'Chưa có lời đọc.'}</p></div>
       {!status?.providers[provider]&&<div className="inline-warning"><AlertCircle size={16}/><span>Chưa kết nối {provider==='vbee'?'Vbee':'Azure'}. <button onClick={()=>setSettings(true)}>Xem cấu hình</button> hoặc nhập audio bên dưới.</span></div>}
       <button className="button primary full" disabled={!!busy||!status?.providers[provider]||!scene.text.trim()||(provider==='vbee'&&scene.text.length>300)} onClick={()=>void run('Đang gửi yêu cầu voice',async()=>{const p=await save();const job=await api<Job>('/api/actions',{action:'voice',projectId:p.id,revision:p.revision,sceneId:scene.id,provider,voiceId,speed});setJobs(list=>[job,...list]);})}><Mic size={16}/> Tạo giọng cho cảnh này</button>
       <button className="button secondary full" disabled={!!busy} onClick={()=>voiceInput.current?.click()}><Upload size={16}/> Nhập MP3 / WAV</button>
       {voiceAsset&&<div className="audio-output"><div className="section-label">OUTPUT · GIỌNG ĐỌC</div><p>{voiceAsset.name} · {voiceAsset.duration?.toFixed(1)}s</p><audio controls src={assetUrl(project,voiceAsset.id)}/>{scene.voice?.text!==scene.text&&<p className="warning-text">Lời đọc đã thay đổi. Cần tạo lại hoặc thay audio.</p>}<button className="text-button" onClick={()=>patchScene({voice:undefined})}>Gỡ giọng đọc khỏi cảnh</button></div>}
       {jobs.filter(j=>j.kind==='voice').slice(0,3).map(j=><JobCard key={j.id} job={j} project={project} onCancel={()=>void api('/api/actions',{action:'cancel',jobId:j.id})}/>)}
      </>}
      {stage==='studio'&&<>
       {scene.kind==='body'&&<BodyFraming scene={scene} aspect={project.aspect} onChange={patchScene}/>}

       <label>Hiển thị khung tiêu đề<select aria-label="Chế độ tiêu đề" value={project.titleMode||'intro'} onChange={e=>patch(p=>({...p,titleMode:e.target.value as Project['titleMode']}))}><option value="intro">Chỉ Intro</option><option value="all">Toàn video</option></select><small>Chỉ Intro: ẩn khung ở phần nội dung. Toàn video: giữ cùng tiêu đề xuyên suốt, phụ đề ở phía trên.</small></label>
       <label>Tiêu đề bản tin cố định<textarea aria-label="Tiêu đề bản tin cố định" rows={3} maxLength={140} value={project.newsTitle||''} placeholder={project.scenes.find(s=>s.kind==='intro')?.headline||project.title} onChange={e=>patch(p=>({...p,newsTitle:e.target.value}))}/><small>Để trống sẽ dùng tiêu đề cảnh Intro.</small></label>
       <div className="info-box"><Monitor size={18}/><div><strong>Xem thử giao diện nền tảng</strong><p>Chọn nền tảng chỉ thay lớp phủ xem trước. Vị trí logo, Sign, watermark, tiêu đề và video giữ nguyên để bạn kiểm tra chỗ bị che.</p></div></div>

       <div className="section-label">CHỌN PHONG CÁCH <span>7 mẫu thiết kế</span></div>
       <div className="templates reference-templates">{STUDIO_TEMPLATES.map(t=><button key={t.id} aria-label={`Phong cách ${t.name}`} className={`template-card ${project.template===t.id?'chosen':''}`} onClick={()=>patch(p=>({...p,template:t.id,brand:{...p.brand,color:t.color}}))}><TemplateSwatch kind={t.id}/><div><strong>{t.name}</strong>{project.template===t.id&&<CheckCircle2 size={15}/>}<small>{t.detail}</small></div></button>)}</div>
       <CustomStyles project={project} busy={!!busy} onPatch={patch} onUpload={(file,layout)=>void upload([file],'style',layout)}/>
       <details className="legacy-templates"><summary>Mẫu đơn giản trước đây</summary><div>{LEGACY_TEMPLATES.map(t=><button key={t.id} className="button secondary" onClick={()=>patch(p=>({...p,template:t.id,brand:{...p.brand,color:t.color}}))}>{t.name}{project.template===t.id&&<Check size={12}/>}</button>)}</div></details>
       {!['sports','cinema','shorts','custom'].includes(project.template)&&<label>Vị trí theo mẫu<select aria-label="Vị trí theo mẫu" value={project.design?.placement||'safe'} onChange={e=>patch(p=>({...p,design:{...(p.design||defaultDesign()),placement:e.target.value as 'safe'|'reference'}}))}><option value="safe">Gọn phía dưới · theo nền tảng</option><option value="reference">Sát ảnh mẫu · khung xuống thấp</option></select><small>Bố cục sát mẫu phù hợp ảnh bìa; kiểm tra vùng che của nền tảng khi đăng video.</small></label>}
       <FrameControls project={project} onPatch={patch}/>
       {project.template==='spotlight'&&<><label>Cụm chữ nhấn màu cam<input aria-label="Cụm chữ nhấn màu" placeholder="Messi, Yamal, chung kết" value={(project.design?.highlightTerms||[]).join(', ')} onChange={e=>patch(p=>({...p,design:{...(p.design||defaultDesign()),highlightTerms:e.target.value.split(',').map(t=>t.trim()).slice(0,16)}}))}/><small>Ngăn cách từng cụm bằng dấu phẩy.</small></label><label>Màu nhấn<input aria-label="Màu nhấn" type="color" value={project.design?.accent||'#ff671e'} onChange={e=>patch(p=>({...p,design:{...(p.design||defaultDesign()),accent:e.target.value}}))}/></label>{[0,1].map(i=><label key={i}>Ảnh tròn {i+1} của cảnh<select aria-label={`Ảnh tròn ${i+1}`} value={scene.insetIds?.[i]||''} onChange={e=>{const ids=[...(scene.insetIds||[])];if(e.target.value)ids[i]=e.target.value;else ids.splice(i,1);patchScene({insetIds:ids.filter(Boolean)});}}><option value="">Không hiển thị</option>{project.assets.filter(a=>a.kind==='image').map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>)}</>}
       {project.template==='magenta'&&<><label className="toggle-label">Hàng biểu tượng mạng xã hội<input type="checkbox" checked={project.design?.showSocials??true} onChange={e=>patch(p=>({...p,design:{...(p.design||defaultDesign()),showSocials:e.target.checked}}))}/></label><label>Tên kênh trên mẫu<input aria-label="Tên kênh trên mẫu" maxLength={40} placeholder="@tenkenh" value={project.design?.socialHandle||''} onChange={e=>patch(p=>({...p,design:{...(p.design||defaultDesign()),socialHandle:e.target.value}}))}/></label></>}
       <div className="section-label">NHẬN DIỆN THƯƠNG HIỆU <Palette size={14}/></div>
       <label>Hiển thị thương hiệu<select aria-label="Hiển thị thương hiệu" value={project.brand.display||'both'} onChange={e=>patch(p=>({...p,brand:{...p.brand,display:e.target.value as Project['brand']['display']}}))}><option value="both">Logo + tên thương hiệu</option><option value="logo">Chỉ logo</option><option value="name">Chỉ tên thương hiệu</option></select><small>Chưa có logo sẽ dùng tên thương hiệu.</small></label>
       <label>Tên thương hiệu<input value={project.brand.name} maxLength={30} onChange={e=>patch(p=>({...p,brand:{...p.brand,name:e.target.value}}))}/></label>
       <label>Kích cỡ tên thương hiệu <span className="value-badge">{Math.round((project.brand.nameScale??1)*100)}%</span><input aria-label="Kích cỡ tên thương hiệu" type="range" min="50" max="300" step="5" value={Math.round((project.brand.nameScale??1)*100)} disabled={project.brand.display==='logo'&&!!project.brand.logoId} onChange={e=>patch(p=>({...p,brand:{...p.brand,nameScale:Number(e.target.value)/100}}))}/><small>50–300% · Chỉnh riêng cỡ chữ; tên dài tự co để vừa khung. Dải xanh cao theo chữ, không theo logo.</small></label>
       <div className="field-row"><label>Màu chủ đạo<div className="color-field"><input aria-label="Màu chủ đạo" type="color" value={project.brand.color} onChange={e=>patch(p=>({...p,brand:{...p.brand,color:e.target.value}}))}/><span>{project.brand.color}</span></div></label><label>Watermark<input value={project.brand.watermark} maxLength={40} onChange={e=>patch(p=>({...p,brand:{...p.brand,watermark:e.target.value}}))}/></label></div>
       <label>Logo<select aria-label="Logo" value={project.brand.logoId||''} onChange={e=>patch(p=>({...p,brand:{...p.brand,logoId:e.target.value||undefined}}))}><option value="">Chưa chọn logo</option>{project.assets.filter(a=>a.kind==='image').map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>
       <div className="studio-upload"><button className="button secondary full" disabled={!!busy} onClick={()=>logoInput.current?.click()}><Upload size={15}/> Tải logo</button><small>PNG, JPG, WebP · Nên dùng PNG nền trong suốt.</small></div>
       <label>Kích cỡ logo <span className="value-badge">{Math.round((project.brand.logoScale??1)*100)}%</span><input aria-label="Kích cỡ logo" type="range" min="50" max="1000" step="5" disabled={!project.brand.logoId||project.brand.display==='name'} value={Math.round((project.brand.logoScale??1)*100)} onChange={e=>patch(p=>({...p,brand:{...p.brand,logoScale:Number(e.target.value)/100}}))}/><small>{!project.brand.logoId?'Tải hoặc chọn logo để điều chỉnh.':project.brand.display==='name'?'Chọn chế độ có logo để xem thay đổi.':'50–1000% · Logo tự giới hạn để vừa vùng hiển thị; áp dụng cả video xuất.'}</small></label>
       <label>Bo góc logo <span className="value-badge">{project.brand.logoRoundness??0}%</span><input aria-label="Bo góc logo" type="range" min="0" max="100" step="1" disabled={!project.brand.logoId||project.brand.display==='name'} value={project.brand.logoRoundness??0} onChange={e=>patch(p=>({...p,brand:{...p.brand,logoRoundness:Number(e.target.value)}}))}/><small>0%: giữ hình gốc · 1–99%: khung vuông bo góc · 100%: hình tròn. Khung bo góc cắt ảnh từ giữa.</small></label>
       <button className="text-button" disabled={!project.brand.logoId||(project.brand.logoScale??1)===1} onClick={()=>patch(p=>({...p,brand:{...p.brand,logoScale:1}}))}>Đặt lại kích cỡ logo</button>
       <label>Nhạc nền<select aria-label="Nhạc nền" value={project.musicId||''} onChange={e=>patch(p=>({...p,musicId:e.target.value||undefined}))}><option value="">Không có nhạc nền</option>{project.assets.filter(a=>a.kind==='audio').map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>
       <div className="studio-upload"><button className="button secondary full" disabled={!!busy} onClick={()=>musicInput.current?.click()}><Upload size={15}/> Tải nhạc nền</button><small>MP3, WAV, M4A · Tối đa 100 MB/file.</small></div>
       <label>Âm lượng nhạc <span className="value-badge">{Math.round(project.musicVolume*100)}%</span><input type="range" min="0" max="0.5" step="0.01" value={project.musicVolume} onChange={e=>patch(p=>({...p,musicVolume:Number(e.target.value)}))}/><small>Nhạc được hạ thêm khi cảnh có lời đọc.</small></label>
      </>}
      {stage==='output'&&<>
       <div className="output-hero"><span className="upload-icon"><Download size={25}/></span><h2>Sẵn sàng lên sóng.</h2><p>Xem lại câu chuyện của bạn trước khi xuất bản.</p></div>
       <div className="export-stats"><div><strong>{formatTime(total/FPS)}</strong><small>Thời lượng</small></div><div><strong>{project.aspect}</strong><small>Khung hình</small></div><div><strong>30</strong><small>FPS</small></div></div>
       <label>Chất lượng xuất<select value={preset} onChange={e=>{setPreset(e.target.value as 'draft'|'full');setApproved(false);}}><option value="full">Bản chính · {d.width} × {d.height} · MP4</option><option value="draft">Bản nháp · {d.width/3} × {d.height/3} · nhanh hơn</option></select></label>
       <div className="review-checklist"><p><CheckCircle2 size={16}/> {project.scenes.length} cảnh trong timeline</p><p><CheckCircle2 size={16}/> Logo, watermark và template đã áp dụng</p><p className={project.scenes.some(s=>!s.voice)?'warning-text':''}><Volume2 size={16}/> {project.scenes.filter(s=>s.voice).length}/{project.scenes.length} cảnh có voice</p>{project.scenes.some(s=>!s.voice)&&<small>Cảnh chưa có voice sẽ chỉ có nhạc hoặc tiếng gốc nếu bật.</small>}{errors.map(e=><p className="warning-text" key={e}><AlertCircle size={15}/>{e}</p>)}</div>
       <label className="check-label"><input type="checkbox" checked={approved} onChange={e=>setApproved(e.target.checked)}/> Tôi đã xem bản dựng, kiểm tra nội dung và quyền sử dụng tư liệu.</label>
       <button className="button primary full" disabled={!!busy||!approved||errors.length>0||!status?.worker} onClick={startRender}><Download size={16}/> Render video {preset==='draft'?'nháp':'bản chính'}</button>
       {!status?.worker&&<p className="warning-text">Worker chưa kết nối. Chạy npm run dev hoặc npm start cùng worker.</p>}
       <button className="button secondary full" onClick={()=>downloadText('phu-de.srt',toSrt(project))}>Tải phụ đề SRT</button>
       <div className="section-label">LỊCH SỬ OUTPUT <span>{jobs.filter(j=>j.kind==='render').length} bản</span></div>
       {jobs.filter(j=>j.kind==='render').map(j=><JobCard key={j.id} job={j} project={project} onCancel={()=>void api('/api/actions',{action:'cancel',jobId:j.id})}/>)}
       <PublishingPanel key={project.id} projectId={project.id} revision={project.revision} jobs={jobs} worker={!!status?.worker}/>
      </>}
     </div>
    </section>
    <section className="preview-panel">
     <div className="preview-toolbar"><span><span className="live-dot"/> BẢN XEM TRƯỚC</span><select aria-label="Tỷ lệ khung hình" value={project.aspect} onChange={e=>patch(p=>({...p,aspect:e.target.value as Project['aspect']}))}><option>9:16</option><option>16:9</option><option>1:1</option></select></div>
     <div className="platform-toolbar"><label>Xem trên <select aria-label="Nền tảng bố cục" disabled={project.aspect!=='9:16'} value={previewPlatform} onChange={e=>{const value=e.target.value as SocialPlatform;setPreviewPlatform(value);localStorage.setItem('crevid-preview-platform',value);}}>{Object.entries(PLATFORMS).map(([id,p])=><option key={id} value={id}>{p.name}</option>)}</select></label><label><input type="checkbox" checked={showPlatform} onChange={e=>setShowPlatform(e.target.checked)}/> Hiện giao diện nền tảng</label>{phonePreview&&<button className="platform-reference-toggle" aria-pressed={showReference} onClick={()=>setShowReference(v=>!v)}>{showReference?'Trở lại video':'Đối chiếu ảnh mẫu'}</button>}</div>
     <div className="preview-stage"><div className={`player-wrap ${project.aspect==='9:16'?'portrait':''} ${phonePreview?'phone-preview':''}`}>
      <div className="player-viewport" data-testid="video-viewport" style={phonePreview?{position:'absolute',left:0,top:`${PREVIEW_VIDEO.y/PHONE.height*100}%`,width:'100%',height:`${PREVIEW_VIDEO.height/PHONE.height*100}%`}:undefined}>
       <Player key={project.id} ref={player} component={NewsVideo} inputProps={{project,mediaBase:''}} initialFrame={12} compositionWidth={d.width} compositionHeight={d.height} durationInFrames={total} fps={FPS} controls={false} clickToPlay style={{width:'100%',aspectRatio:`${d.width}/${d.height}`}} acknowledgeRemotionLicense/>
      </div>
      {phonePreview&&<PlatformGuide platform={previewPlatform}/>}
      {phonePreview&&showReference&&<img className="platform-reference-image" data-testid="platform-reference-image" src={platformPreset.reference} alt={`Ảnh mẫu gốc ${platformPreset.name} · 591 × 1280`}/>}
     </div></div>
     <div className="preview-playback"><button aria-label={playing?'Tạm dừng xem trước':'Phát xem trước'} onClick={()=>playing?player.current?.pause():player.current?.play()}>{playing?'Ⅱ':<Play size={15}/>}</button><input aria-label="Vị trí xem trước" type="range" min="0" max={total-1} value={Math.min(frame,total-1)} onChange={e=>player.current?.seekTo(Number(e.target.value))}/><span>{formatTime(frame/FPS)} / {formatTime(total/FPS)}</span></div>
     <div className="preview-foot"><span><Monitor size={14}/> {d.width} × {d.height}</span><span>30 fps</span></div>
     <div className="preview-tip">{project.aspect==='9:16'?'Khung điện thoại 591 × 1280 theo ảnh mẫu · video giữ tỷ lệ 9:16 · UI không xuất vào MP4':'Chuyển sang 9:16 để xem Facebook Reels / YouTube Shorts / TikTok'}</div>
    </section>
    <aside className="inspector"><div className="inspector-title"><Settings2 size={17}/><strong>Thuộc tính cảnh</strong><span>{String(selectedIndex+1).padStart(2,'0')}</span></div><div className="panel-scroll"><div className="scene-kind"><span className={`kind-dot ${scene.kind}`}/>{kindName[scene.kind]}<small>SCENE {selectedIndex+1}</small></div><label>Loại cảnh<select aria-label="Loại cảnh" value={scene.kind} onChange={e=>patchScene({kind:e.target.value as Scene['kind']})}><option value="intro">Mở đầu / Intro</option><option value="body">Nội dung / Body</option></select></label><label>Thời lượng tối thiểu<div className="input-with-unit"><input aria-label="Thời lượng cảnh" type="number" min="1" max="180" step="0.1" value={scene.duration} onChange={e=>patchScene({duration:Math.max(1,Math.min(180,Number(e.target.value)||1))})}/><span>giây</span></div><small>Thực tế: {(sceneFrames(scene,project.assets)/FPS).toFixed(1)}s · tự mở rộng theo voice.</small></label><div className="thin-divider"/><label>Nhãn / Sign<input aria-label="Nhãn bản tin" value={scene.tag} maxLength={40} onChange={e=>patchScene({tag:e.target.value})}/></label><label>Độ mờ Sign <span className="value-badge">{Math.round((1-(scene.signOpacity??1))*100)}%</span><input aria-label="Độ mờ Sign" type="range" min="0" max="100" step="1" value={Math.round((1-(scene.signOpacity??1))*100)} onChange={e=>patchScene({signOpacity:1-Number(e.target.value)/100})}/><small>0%: rõ hoàn toàn · 100%: ẩn Sign.</small></label><label className="toggle-label">Hiện phụ đề<input type="checkbox" checked={scene.showCaption} onChange={e=>patchScene({showCaption:e.target.checked})}/></label><div className="thin-divider"/><label>Tư liệu của cảnh<select value={scene.mediaId||''} onChange={e=>patchScene({mediaId:e.target.value||undefined})}><option value="">Nền minh họa</option>{project.assets.filter(a=>a.kind!=='audio').map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>{scene.kind==='body'&&stage!=='studio'&&<BodyFraming scene={scene} aspect={project.aspect} onChange={patchScene}/>}
     {selectedMedia&&<MediaControls scene={scene} asset={selectedMedia} onChange={patchScene}/>}
     {stage!=='script'&&<label>Lời đọc của cảnh<textarea aria-label="Lời đọc của cảnh" rows={5} maxLength={3000} placeholder="Nhập lời đọc cho ảnh/video này…" value={scene.text} onChange={e=>patchScene({text:e.target.value})}/><small>Tạo giọng AI cho cảnh đang chọn ở bước Voice, hoặc nhập bản thu riêng.</small><button className="text-button" onClick={()=>setStage('voice')}>Tạo / nhập giọng đọc</button></label>}
     <div className="thin-divider"/><div className="section-label">INPUT → OUTPUT</div><div className="io-row"><span>Tư liệu</span><strong>{selectedMedia?'Đã gắn':'Nền mẫu'}</strong></div><div className="io-row"><span>Kịch bản</span><strong>{scene.text.trim()?'Có nội dung':'Chưa nhập'}</strong></div><div className="io-row"><span>Giọng đọc</span><strong className={scene.voice&&scene.voice.text!==scene.text?'warning-text':''}>{scene.voice?(scene.voice.text===scene.text?'Đã gắn':'Cần cập nhật'):'Chưa có'}</strong></div><div className="io-row"><span>Phiên bản lưu</span><strong>v{project.revision}</strong></div></div></aside>
   </main>
   <section className="timeline-panel" inert={busy?true:undefined}><div className="timeline-heading"><div><Layers size={16}/><strong>Timeline</strong><span>{project.scenes.length} cảnh · {formatTime(total/FPS)}</span></div><div><button className="icon-button" aria-label="Di chuyển cảnh lên" disabled={selectedIndex===0} onClick={()=>patch(p=>{const list=[...p.scenes];[list[selectedIndex-1],list[selectedIndex]]=[list[selectedIndex],list[selectedIndex-1]];return {...p,scenes:list};})}><ArrowUp size={15}/></button><button className="icon-button" aria-label="Di chuyển cảnh xuống" disabled={selectedIndex===project.scenes.length-1} onClick={()=>patch(p=>{const list=[...p.scenes];[list[selectedIndex+1],list[selectedIndex]]=[list[selectedIndex],list[selectedIndex+1]];return {...p,scenes:list};})}><ArrowDown size={15}/></button><button className="icon-button" aria-label="Xóa cảnh" disabled={project.scenes.length===1} onClick={()=>{const next=project.scenes.filter(s=>s.id!==scene.id);patch(p=>({...p,scenes:next}));setSelected(next[0].id);}}><Trash2 size={15}/></button><span className="tiny-divider"/><button className="text-button" disabled={project.scenes.length>=30} onClick={()=>{const s=newScene();patch(p=>({...p,scenes:[...p.scenes,s]}));setSelected(s.id);}}><Plus size={15}/> Thêm cảnh</button><button className="text-button" disabled={!!busy||project.scenes.length>=30} onClick={()=>bodyInput.current?.click()}><Upload size={15}/> Tải ảnh/video tạo cảnh</button></div></div><div className="timeline-scroll"><div className="track-label"><Film size={14}/><span>HÌNH ẢNH</span><Mic size={14}/><span>GIỌNG ĐỌC</span></div><div className="scene-track">{timeline(project).map(({scene:s,from,duration},i)=><button key={s.id} className={`scene-clip ${scene.id===s.id?'selected':''}`} onClick={()=>chooseScene(s)}><span className="clip-time">{formatTime(from/FPS)}</span><div className={`clip-body ${s.kind}`}><span className="clip-number">{String(i+1).padStart(2,'0')}</span><span className="clip-copy"><strong>{kindName[s.kind]}</strong><small>{s.headline}</small></span><span className="clip-duration">{(duration/FPS).toFixed(1)}s</span></div><div className={`voice-track ${s.voice?'has-voice':''}`}><Mic size={10}/>{s.voice?<span className="wave-bars">▂▅▃▆▇▃▂▆▅▂▅▇▃▆▅▂▇▅▃▆▂▅▇▃</span>:<span>Chưa có voice</span>}</div></button>)}</div></div></section>
   <footer className="statusbar"><span><span className={`live-dot ${status?.worker?'':'offline'}`}/> {status?.worker?'Render worker sẵn sàng':'Đang kiểm tra worker'}{hasPending?' · Có tác vụ đang xử lý':''}</span><span>Cre-vid v0.1 <i>·</i> Lưu trên máy này</span></footer>
  </div>
  <input ref={fileInput} aria-label="Tư liệu thư viện" type="file" hidden multiple accept="image/jpeg,image/png,image/webp,video/mp4,video/quicktime,audio/mpeg,audio/wav,audio/x-wav,audio/mp4" onChange={e=>{void upload(e.target.files);e.target.value='';}}/>
  <input ref={bodyInput} aria-label="Tư liệu tạo nội dung" type="file" hidden multiple accept=".jpg,.jpeg,.png,.webp,.mp4,.mov" onChange={e=>{void upload(e.target.files,'body');e.target.value='';}}/>
  <input ref={voiceInput} type="file" hidden accept=".mp3,.wav,.m4a" onChange={e=>{void upload(e.target.files,'voice');e.target.value='';}}/>
  <input ref={logoInput} aria-label="File logo" type="file" hidden accept=".png,.jpg,.jpeg,.webp" onChange={e=>{void upload(e.target.files,'logo');e.target.value='';}}/>
  <input ref={musicInput} aria-label="File nhạc nền" type="file" hidden accept=".mp3,.wav,.m4a" onChange={e=>{void upload(e.target.files,'music');e.target.value='';}}/>
  {settings&&<div className="modal-backdrop" onClick={()=>setSettings(false)}><section className="modal" role="dialog" aria-modal="true" aria-label="Cấu hình giọng đọc" onClick={e=>e.stopPropagation()}><button className="modal-close" aria-label="Đóng cấu hình" onClick={()=>setSettings(false)}><X/></button><span className="eyebrow">KẾT NỐI DỊCH VỤ</span><h2>Giọng đọc cho Studio</h2><p>Thêm khóa của bạn vào file <code>.env.local</code> trong thư mục dự án, rồi khởi động lại web và worker. Khóa được giữ ở server.</p><div className="connection"><strong>Vbee · Ngọc Huyền</strong><span>{status?.providers.vbee?'Đã cấu hình':'Chưa cấu hình'}</span></div><pre>VBEE_APP_ID=…{'\n'}VBEE_TOKEN=…{'\n'}VBEE_VOICE_CODE=hn_female_ngochuyen_full_48k-fhg</pre><a href="https://api-docs.vbee.vn/tao-ung-dung-app-id-va-token" target="_blank" rel="noreferrer">Hướng dẫn lấy App ID và Token <ExternalLink size={13}/></a><div className="connection"><strong>Azure Speech</strong><span>{status?.providers.azure?'Đã cấu hình':'Chưa cấu hình'}</span></div><pre>AZURE_SPEECH_KEY=…{'\n'}AZURE_SPEECH_REGION=southeastasia</pre><div className="info-box"><Upload size={19}/><p>Bạn luôn có thể tạo voice bên ngoài và nhập MP3/WAV vào từng cảnh.</p></div></section></div>}
 </div>;
}
function JobCard({job:j,project:p,onCancel}:{job:Job;project:Project;onCancel:()=>void}){const pending=['queued','running'].includes(j.state);const labels={queued:'Đang chờ',running:'Đang xử lý',succeeded:'Hoàn thành',failed:'Thất bại',canceled:'Đã hủy'};return <div className="job-card"><div><strong>{j.kind==='render'?(j.options.preset==='draft'?'Video nháp':'Video bản chính'):'Giọng đọc'}</strong><span className={`job-state ${j.state}`}>{labels[j.state]}</span></div><small>Phiên bản {j.revision} · {new Date(j.createdAt).toLocaleTimeString('vi-VN',{hour:'2-digit',minute:'2-digit'})}{j.elapsed?` · ${j.elapsed.toFixed(1)} giây`:''}</small>{pending&&<><div className="progress"><i style={{width:`${j.progress}%`}}/></div><p>{j.message} <span>{j.progress}%</span></p><button className="text-button" onClick={onCancel}>Hủy tác vụ</button></>}{j.error&&<p className="warning-text">{j.error}</p>}{j.state==='succeeded'&&<div className="output-links">{j.outputs?.map(o=><a key={o.file} href={`/api/media/${p.id}/${o.file}?download=1`} download><Download size={12}/>{o.name}</a>)}</div>}{j.state==='succeeded'&&j.kind==='render'&&<video className="render-preview" controls preload="metadata" src={`/api/media/${p.id}/${j.id}.mp4`}/>}</div>;}
