import React,{useEffect,useState} from 'react';
import {AbsoluteFill,Sequence,Img,OffthreadVideo,Audio,Loop,useCurrentFrame,useVideoConfig,staticFile,delayRender,continueRender,cancelRender} from 'remotion';
import {type Project,type Scene,assetUrl,timeline,captions,FPS} from '../lib/model';
import {sceneAudio} from '../lib/scene-audio';
import {imageMotion} from './image-motion';
import {bodyWindow} from './body-layout';
import {newsLayout} from './layout';
import {FittedTitle} from './FittedTitle';
import {BrandMark} from './BrandMark';
import {ReferenceOverlay} from './ReferenceOverlay';
export type VideoProps={project:Project;mediaBase?:string};
const fontCss=[400,700,800].flatMap(weight=>['latin','vietnamese'].map(subset=>`@font-face{font-family:News;src:url('${staticFile(`fonts/be-vietnam-pro-${subset}-${weight}-normal.woff2`)}') format('woff2');font-style:normal;font-weight:${weight};${subset==='vietnamese'?'unicode-range:U+0102-0103,U+0110-0111,U+0128-0129,U+0168-0169,U+01A0-01A1,U+01AF-01B0,U+0300-0301,U+0303-0304,U+0308-0309,U+0323,U+0329,U+1EA0-1EF9,U+20AB;':''}}`)).join('');
const condensedCss=['latin','vietnamese'].map(subset=>`@font-face{font-family:NewsCondensed;src:url('${staticFile(`fonts/oswald-${subset}-600-normal.woff2`)}') format('woff2');font-style:normal;font-weight:600;${subset==='vietnamese'?'unicode-range:U+0102-0103,U+0110-0111,U+0128-0129,U+0168-0169,U+01A0-01A1,U+01AF-01B0,U+0300-0301,U+0303-0304,U+0308-0309,U+0323,U+0329,U+1EA0-1EF9,U+20AB;':''}}`).join('');
function FontLoader(){const [handle]=useState(()=>delayRender('Đang tải font tiếng Việt'));useEffect(()=>{Promise.all([document.fonts.load('600 48px NewsCondensed','Tiếng Việt Hà Nội'),document.fonts.load('700 48px News','Tiếng Việt Hà Nội'),document.fonts.load('400 48px News','Tiếng Việt Hà Nội'),document.fonts.load('800 48px News','Tiếng Việt Hà Nội')]).then(()=>continueRender(handle)).catch(cancelRender);},[handle]);return <style>{fontCss+condensedCss}</style>;}
function ScenicBackground(){return <AbsoluteFill style={{background:'linear-gradient(160deg,#183b53,#457986 52%,#d9bd88)'}}><svg viewBox="0 0 1080 1920" preserveAspectRatio="xMidYMid slice" style={{width:'100%',height:'100%'}}><circle cx="790" cy="370" r="120" fill="#eddcb1" opacity=".8"/><path d="M0 1100L160 700L310 980L530 610L710 900L910 670L1080 900V1920H0Z" fill="#2b6368"/><path d="M0 1270L200 990L360 1250L590 910L850 1170L1080 1010V1920H0Z" fill="#1a4549"/><path d="M0 1440Q300 1270 600 1450T1080 1390V1920H0Z" fill="#153438"/></svg></AbsoluteFill>;}
function SceneView({project:p,scene:s,mediaBase,from,duration}:{project:Project;scene:Scene;mediaBase?:string;from:number;duration:number}){
 const frame=useCurrentFrame();const {width,height}=useVideoConfig();const portrait=height>width;const scale=width/1080;const unit=portrait?1:height/1920;const media=p.assets.find(a=>a.id===s.mediaId);const audio=sceneAudio(s,p.assets);const voice=assetUrl(p,audio.voice?.id,mediaBase);const mediaSrc=assetUrl(p,s.mediaId,mediaBase);
 const cue=captions(p).find(c=>c.start<=(from+frame)/FPS&&c.end>(from+frame)/FPS);
 const layout=newsLayout(p,s);
 const breaking=p.template==='breaking';const minimal=p.template==='minimal';
 const fontScale=portrait?scale:height/1080;
 const headlineSize=(layout.compact?40:layout.title.length>100?39:layout.title.length>65?45:54)*fontScale;
 const window=bodyWindow(s,width,height,media);const isBody=s.kind==='body';
 const mediaStyle:React.CSSProperties={width:'100%',height:'100%',objectFit:s.fit,objectPosition:`${s.cropX}% ${s.cropY}%`};
 const motion=media?.kind==='image'?imageMotion(s,frame,duration,window.width):undefined;
 const renderMedia=(background=false)=>mediaSrc&&media?.kind==='image'?<Img src={mediaSrc} style={{...mediaStyle,...(background?{objectFit:'cover'}:{})}}/>:mediaSrc&&media?.kind==='video'?<Loop durationInFrames={Math.max(1,Math.floor(((media.duration||1)-s.trimStart)*FPS))}><OffthreadVideo src={mediaSrc} trimBefore={Math.floor(s.trimStart*FPS)} muted={background||audio.originalVolume===0} volume={background?0:audio.originalVolume} style={{...mediaStyle,...(background?{objectFit:'cover'}:{})}}/></Loop>:<ScenicBackground/>;
 return <AbsoluteFill style={{background:'#142228',fontFamily:'News, sans-serif',color:'white'}}>
  {window.framed&&<AbsoluteFill data-testid="body-blur" style={{filter:`blur(${32*scale}px)`,transform:'scale(1.08)'}}>{renderMedia(true)}</AbsoluteFill>}
  <div data-testid="body-media-window" data-layout={isBody?s.bodyLayout||'full':'full'} style={{position:'absolute',left:window.x,top:window.y,width:window.width,height:window.height,overflow:'hidden',background:'#142228'}}><div data-testid="media-motion" style={{width:'100%',height:'100%',transform:motion?.transform,transformOrigin:'center'}}>{renderMedia()}</div></div>
  <AbsoluteFill style={{background:'linear-gradient(180deg,rgba(0,0,0,.15),transparent 38%,rgba(0,0,0,.66))'}}/>
  {layout.reference&&layout.showTitle&&<ReferenceOverlay key={`${p.template}-${p.aspect}-${p.design?.placement}-${layout.titleHeight}-${layout.titleBottom}`} project={p} scene={s} mediaBase={mediaBase}/>}
  {(!layout.reference||!layout.showTitle)&&<div data-testid="scene-brand" style={{position:'absolute',top:height*layout.labelTop,...(isBody?{right:width*layout.right}:{left:width*layout.left}),display:'flex',alignItems:'center',gap:16*fontScale,fontSize:27*fontScale,fontWeight:800,letterSpacing:2}}><BrandMark project={p} mediaBase={mediaBase} size={27*fontScale} maxHeight={height*.24} align={isBody?'right':'left'} maxWidth={width*(isBody?.36:1-layout.left-layout.right)}/></div>}
  <div data-testid="news-watermark" style={{position:'absolute',maxWidth:width*(isBody?.36:1-layout.left-layout.right),overflowWrap:'anywhere',top:height*(layout.compact?layout.labelTop+.10:.24),left:width*layout.left,fontSize:26*fontScale,fontWeight:700,opacity:.3,letterSpacing:2}}>{p.brand.watermark}</div>
  {s.tag&&<div data-testid="news-sign" style={{opacity:s.signOpacity??1,position:'absolute',left:width*layout.left,top:height*(layout.labelTop+.06),maxWidth:width*(1-layout.left-layout.right),background:breaking?p.brand.color:'#faf7ee',color:breaking?'white':'#182c37',padding:`${10*fontScale}px ${20*fontScale}px`,fontSize:23*fontScale,fontWeight:800,letterSpacing:1,overflowWrap:'normal',wordBreak:'normal'}}>{s.tag}</div>}
  {layout.showTitle&&!layout.reference&&<div data-testid="title-panel" style={{position:'absolute',left:width*layout.left,right:width*layout.right,bottom:height*layout.titleBottom,height:height*layout.titleHeight,opacity:1,background:breaking?p.brand.color:minimal?'rgba(0,0,0,.48)':'rgba(15,27,34,.92)',borderLeft:minimal?`${5*fontScale}px solid ${p.brand.color}`:undefined,padding:`${24*fontScale}px ${28*fontScale}px`,display:'flex',alignItems:'center',fontSize:headlineSize,fontWeight:800,lineHeight:1.27,whiteSpace:'pre-wrap',overflowWrap:'normal',wordBreak:'normal',boxSizing:'border-box'}}><FittedTitle key={layout.titleHeight} text={layout.title} maxSize={headlineSize} minSize={18*fontScale} center>{layout.title}</FittedTitle></div>}
  {s.source&&<div data-testid="news-source" style={{position:'absolute',left:width*layout.left,right:width*layout.right,...(layout.reference?{top:height*(layout.compact?layout.labelTop:.10)}:{bottom:height*(layout.titleBottom-.035)}),fontSize:18*fontScale,color:'#e3e8e9',whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis'}}>Nguồn: {s.source}</div>}
  {cue&&<div data-testid="news-caption" style={{position:'absolute',bottom:height*(layout.showTitle?layout.captionBottom:layout.standaloneCaptionBottom),left:width*layout.left,right:width*layout.right,textAlign:'center',fontSize:34*fontScale,fontWeight:700,lineHeight:1.45,overflowWrap:'normal',wordBreak:'normal'}}><span style={{background:'rgba(0,0,0,.78)',padding:`${6*fontScale}px ${12*fontScale}px`,boxDecorationBreak:'clone',WebkitBoxDecorationBreak:'clone'}}>{cue.text}</span></div>}
  {voice&&<Audio src={voice} volume={1}/>}
 </AbsoluteFill>;
}
export function NewsVideo({project,mediaBase=''}:VideoProps){const frame=useCurrentFrame();const active=timeline(project).find(s=>frame>=s.from&&frame<s.from+s.duration);const hasVoice=active?!!sceneAudio(active.scene,project.assets).voice:false;const music=project.assets.find(a=>a.id===project.musicId);return <AbsoluteFill><FontLoader/>{timeline(project).map(({scene,from,duration})=><Sequence key={scene.id} from={from} durationInFrames={duration}><SceneView project={project} scene={scene} from={from} duration={duration} mediaBase={mediaBase}/></Sequence>)}{music&&<Loop durationInFrames={Math.max(1,Math.floor((music.duration||1)*FPS))}><Audio src={assetUrl(project,music.id,mediaBase)!} volume={project.musicVolume*(hasVoice?0.6:1)}/></Loop>}</AbsoluteFill>;}
